version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis                                    
    restart: unless-stopped       
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly no
    volumes:                                                      
      - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/data:/data"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "16379:6379"