version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes: 
      - "/etc/localtime:/etc/localtime" ## kafka 镜像和宿主机器之间时间保持一致
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
    ports:
      - "9092:9092"
  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: kafka-map
    restart: unless-stopped
    depends_on:
      - kafka
    volumes: 
      - "./mount/kafka-map/data:/usr/local/kafka-map/data"
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
    ports:
      - "9192:8080"
