version: '1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql                                    
    # 指定容器退出后的重启策略为始终重启，但是不考虑在 Docker 守护进程启动时就已经停止了的容器
    restart: unless-stopped       
    # 数据卷挂载路径设置，将本机目录映射到容器目录
    volumes:                                                      
      - "/home/mysql/conf:/etc/mysql/conf.d"
      - "/home/mysql/data:/var/lib/mysql"
      - "/home/mysql/mysql-files:/var/lib/mysql-files"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zeus
    privileged: true
    user: root
    ports:
      - "3306:3306"