version: '3'
services:
  nginx:
    image: registry.cn-shenzhen.aliyuncs.com/alexchen-images/nginx
    container_name: zeus-nginx
    restart: unless-stopped
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"
      - "./mount/root:/data/nginx"
      - "./mount/log:/var/log/nginx"
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "8080:80"