version: '3'
services:
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/alexchen-images/redis
    container_name: zeus-redis                                    
    restart: unless-stopped       
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly no
    volumes:                                                      
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./mount/data:/data"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "6379:6379"
