version: '3'

networks:
  elastic:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      # - "./plugins:/usr/share/elasticsearch/plugins"
      - "./mount/data:/usr/share/elasticsearch/data"
      # - "./mount/logs:/usr/share/elasticsearch/logs"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: true
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
