version: '3'
services:
  nginx:
    image: nginx:1.21.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./mount/html:/usr/share/nginx/html"
      - "./mount/root:/data/nginx"
      - "./mount/log:/var/log/nginx"
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "8080:80"