services:
  mysql:
    image: registry.cn-shenzhen.aliyuncs.com/alexchen-images/mysql:8.0
    container_name: zeus-mysql                                    
    restart: unless-stopped       
    volumes:                                                      
      - "./conf/my.cnf:/etc/mysql/my.cnf"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./mount/data:/var/lib/mysql"
      - "./mount/mysql-files:/var/lib/mysql-files"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 2$WtV2iJW0X0iPLF
      MYSQL_USER: zeus
      MYSQL_PASSWORD: 2$WtV2iJW0X0iPLF
    privileged: true
    user: root
    ports:
      - "3306:3306"
