version: '3'
services:
  nginx:
    image: portainer/portainer-ce:2.17.0 
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./mount/data:/data"
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "9000:9000"
    privileged: true