version: '3' 
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql                                    
    restart: unless-stopped       
    volumes:                                                      
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/mysql-files:/var/lib/mysql-files"
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root
    privileged: true
    user: root
    ports:
      - "3306:3306"
