version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis                                    
    restart: unless-stopped       
    command: redis-server /etc/redis/redis.conf --requirepass 1qaz@wsx?S --appendonly no
    volumes:                                                      
      - "/home/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/home/docker/redis/data:/data"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "16379:6379"